# SPDX-FileCopyrightText: 2026 H2Lab Development Team
# SPDX-License-Identifier: Apache-2.0

[tox]
envlist = py312, lint, typecheck
isolated_build = True

[testenv]
deps =
    pytest
commands =
    pytest {posargs}

[testenv:lint]
deps =
    black
    flake8
    flake8-docstrings
commands =
    black --check src
    flake8 src

[testenv:typecheck]
extras = dev
deps =
    mypy
commands =
    mypy src
